### ISSUE TITLE
AVER MANDA TU REPPORTE

### ISSUE THREAD

**Issue by jesoto** [jesoto/Churn-Prediction-Tarjetas-de-credito#1]
MANO UNA PAVITA P

**Comment by KatiuskaOlivera** [comment]
[Untitled-1.md](https://github.com/jesoto/Churn-Prediction-Tarjetas-de-credito/files/7073243/Untitled-1.md)

**Comment by KiaraHugo37** [comment]
[Untitled-1.md](https://github.com/jesoto/Churn-Prediction-Tarjetas-de-credito/files/7073244/Untitled-1.md)

**Comment by francocv6** [comment]
[Untitled-1.md](https://github.com/jesoto/Churn-Prediction-Tarjetas-de-credito/files/7073247/Untitled-1.md)

**Comment by francocv6** [comment]
Hola

**Comment by jesoto** [comment]
LISTO MIS KINGS
